### ISSUE TITLE
Error: Module version mismatch. Expected 49, got 48.

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1034]
Started getting these again.

```
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/node_modules/dtrace-provider/dtrace-provider.js:17:23)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/victorporof/Work/Mozilla/tofino/.electron/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/victorporof/Work/Mozilla/tofino/.electron/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12) code: 'MODULE_NOT_FOUND' }
```
@Mossop ?

**Comment by Mossop** [comment]
Try npm prune

**Comment by victorporof** [comment]
Neither prune nor clobber work.

**Comment by jsantell** [comment]
Same with me, on 6.3.1

**Comment by jsantell** [comment]
(things seem to be running fine though?)

**Comment by victorporof** [comment]
😂
