### ISSUE TITLE
Error: Cannot find module "./build"

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1455]
Started after https://github.com/mozilla/tofino/pull/1451

@jsantell ?

**Comment by victorporof** [comment]
```
{ Error: Cannot find module "./build"
    at webpackMissingModule (webpack:///./~/dtrace-provider/dtrace-provider.js?:17:67)
    at eval (webpack:///./~/dtrace-provider/dtrace-provider.js?:17:151)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:122:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30)
    at eval (webpack:///./~/bunyan/lib/bunyan.js?:79:18)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:95:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30)
    at eval (webpack:///./app/shared/logging.js?:94:51)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:86:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module "./build"
    at webpackMissingModule (webpack:///./~/dtrace-provider/dtrace-provider.js?:17:67)
    at eval (webpack:///./~/dtrace-provider/dtrace-provider.js?:17:151)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:122:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30)
    at eval (webpack:///./~/bunyan/lib/bunyan.js?:79:18)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:95:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30)
    at eval (webpack:///./app/shared/logging.js?:94:51)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:86:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module "./build"
    at webpackMissingModule (webpack:///./~/dtrace-provider/dtrace-provider.js?:17:67)
    at eval (webpack:///./~/dtrace-provider/dtrace-provider.js?:17:151)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:122:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30)
    at eval (webpack:///./~/bunyan/lib/bunyan.js?:79:18)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:95:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30)
    at eval (webpack:///./app/shared/logging.js?:94:51)
    at Object.<anonymous> (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:86:2)
    at __webpack_require__ (/Users/victorporof/Work/Mozilla/tofino/lib/main/index.js:20:30) code: 'MODULE_NOT_FOUND' }
```
