### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by LouWii** [mozilla/tofino#467]
Hi,

When I try to build the app, I got a `Unexpected token ...` happening.

```
$ npm start

> tofino@0.1.0 start /Users/louis/Documents/code/tofino
> node build/main.js --run

/Users/louis/Documents/code/tofino/build/tasks.js:59
      yield require('./task-test').default([...args, 'test/lint']);})();}, 
                                            ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/louis/Documents/code/tofino/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/louis/Documents/code/tofino/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at handlers.--build.--run (/Users/louis/Documents/code/tofino/build/main.js:34:17)
    at /Users/louis/Documents/code/tofino/build/main.js:72:7

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! tofino@0.1.0 start: `node build/main.js --run`
npm ERR! Exit status 1
```

Is that because I'm using Node 4 and not 5 ?

Thanks

**Comment by Mossop** [comment]
Probably yes, we target node 5 at the moment.

**Comment by victorporof** [comment]
Please update to node 5.
