### ISSUE TITLE
Document (and enforce?) minimum node version

### ISSUE THREAD

**Issue by ismith** [mozilla/tofino#594]
`npm install` fails using node 4.4.3 (error pasted below), but succeeds using node 6.2.0.  Haven't tried versions in between.

```
/Users/ismith/wip/tofino/build/tasks.js:33
      yield _this3.build([...args, '--force']);
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/ismith/wip/tofino/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ismith/wip/tofino/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at handlers.--build.--run.--run-dev (/Users/ismith/wip/tofino/build/main.js:54:17)
    at /Users/ismith/wip/tofino/build/main.js:94:7
```

**Comment by Mossop** [comment]
We do already document that node 6 is required for building: https://github.com/mozilla/tofino/blob/master/docs/building.md.

We also have code that aborts and tells you so but I guess it isn't running early enough here. Thoughts @jsantell?

**Comment by ismith** [comment]
Ah, I missed that piece in building.md - thanks.

**Comment by jsantell** [comment]
I'm guessing the rough checking we do right now requires a version of node >= 4.4.3, unfortunately -- this was just a rough pass and we can be better about the error messaging here
