### ISSUE TITLE
Can't find a local build of electron anymore

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#63]
Started happening after https://github.com/mozilla/tofino/pull/62

After this, `gulp run` is failing on a fresh clone, even after a `npm install`:

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/victorporof/Desktop/tofino/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/version'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.getElectronVersion (utils.js:25:13)
    at Object.<anonymous> (config-builder.js:25:24)
    at Module._compile (module.js:413:34)
    at loader (/Users/victorporof/Desktop/tofino/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/victorporof/Desktop/tofino/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by bgrins** [comment]
Looks good to me

**Comment by gabrielluong** [comment]
This should be closed after fc948f9 merged.

**Comment by victorporof** [comment]
This was failing travis: https://travis-ci.org/mozilla/tofino/builds/122307177

**Comment by Mossop** [comment]
It looks like it failed because you force pushed destroying the commit that Travis was trying to test.

**Comment by victorporof** [comment]
:(

**Comment by victorporof** [comment]
Discussed in #general with @bgrins about changing his merge message to be more descriptive, hence the force push.

**Comment by Mossop** [comment]
The force push passed tests so you can just ignore the failure on the PR
and close this I think.

https://travis-ci.org/mozilla/tofino/builds/122313652

**Comment by victorporof** [comment]
@Mossop problem is, it's showing up in other PRs like https://github.com/mozilla/tofino/pull/71

**Comment by Mossop** [comment]
Strange. I've seen travis get confused with force pushes. Maybe the problem will resolve when something new gets committed?

**Comment by victorporof** [comment]
@Mossop Hopefully.
